FROM debian

# UDP Port
EXPOSE 9987:9987/udp
# Listening port
EXPOSE 10011:10011
# File Transfers port
EXPOSE 30033:30033

RUN apt-get update
RUN apt-get install -y wget
RUN apt-get install -y bzip2
RUN wget http://dl.4players.de/ts/releases/3.0.13.8/teamspeak3-server_linux_amd64-3.0.13.8.tar.bz2
RUN tar -jxf teamspeak3-server_linux_amd64-3.0.13.8.tar.bz2

CMD cd teamspeak3-server_linux_amd64 && ./ts3server_minimal_runscript.sh
