FROM ruby:latest

RUN apt-get update -y && apt-get install -y
CMD curl -sSL https://get.rvm.io
RUN gem install rails
RUN apt-get install nodejs -y

ONBUILD COPY . /opt/app
WORKDIR /opt/app

ONBUILD RUN bundle install
ONBUILD RUN rails db:migrate
ONBUILD RUN rails db:seed
